FROM ubuntu:14.04
MAINTAINER Berkeley Churchill (berkeley@cs.stanford.edu)
ARG TRAVIS=0

# SSH setup
CMD ["/usr/sbin/sshd", "-D"]
EXPOSE 22
ENV NOTVISIBLE "in users profile"
RUN useradd -ms /bin/bash -ms /bin/bash stoke

# Build everything 
COPY src/ext/ /home/stoke/misc/src/ext
COPY src/Makefile /home/stoke/misc
COPY docker /home/stoke/misc/docker
RUN chmod +x /home/stoke/misc/base-setup.sh && \
    TRAVIS=$TRAVIS /home/stoke/misc/base-setup.sh
