##############################################################
#
# This file includes all the test targets as well as all the
# non-default build rules and test recipes.
#
##############################################################


##############################################################
#
# Test targets
#
##############################################################

###### Place all generic definitions here ######

# This defines tests which run tools of the same name.  This is simply for convenience to avoid
# defining the test name twice (once in TOOL_ROOTS and again in TEST_ROOTS).
# Tests defined here should not be defined in TOOL_ROOTS and TEST_ROOTS.
TEST_TOOL_ROOTS := mix-mt

# This defines the tests to be run that were not already defined in TEST_TOOL_ROOTS.
TEST_ROOTS :=

# This defines a list of tests that should run in the "short" sanity. Tests in this list must also
# appear either in the TEST_TOOL_ROOTS or the TEST_ROOTS list.
# If the entire directory should be tested in sanity, assign TEST_TOOL_ROOTS and TEST_ROOTS to the
# SANITY_SUBSET variable in the tests section below (see example in makefile.rules.tmpl).
SANITY_SUBSET :=

# This defines the tools which will be run during the the tests, and were not already defined in
# TEST_TOOL_ROOTS.
TOOL_ROOTS :=

# This defines the static analysis tools which will be run during the the tests. They should not
# be defined in TEST_TOOL_ROOTS. If a test with the same name exists, it should be defined in
# TEST_ROOTS.
# Note: Static analysis tools are in fact executables linked with the Pin Static Analysis Library.
# This library provides a subset of the Pin APIs which allows the tool to perform static analysis
# of an application or dll. Pin itself is not used when this tool runs.
SA_TOOL_ROOTS :=

# This defines all the applications that will be run during the tests.
APP_ROOTS := marker-example

# This defines any additional object files that need to be compiled.
OBJECT_ROOTS :=

# This defines any additional dlls (shared objects), other than the pintools, that need to be compiled.
DLL_ROOTS :=

# This defines any static libraries (archives), that need to be built.
LIB_ROOTS :=

###### Place OS-specific definitions here ######

# Linux
ifeq ($(TARGET_OS),linux)
    TEST_ROOTS += test-mt
    APP_ROOTS += test-mt
    ifeq ($(TARGET),intel64)
        TEST_ROOTS += mix-length
    endif
endif

# Windows
ifeq ($(TARGET_OS),windows)
    OBJECT_ROOTS += assy-support-$(TARGET)
endif

# TODO: These tests fail on Mac - fix and remove the following:
ifeq ($(TARGET_OS),mac)
    TEST_TOOL_ROOTS := $(TEST_TOOL_ROOTS:mix-mt=)
endif


##############################################################
#
# Test recipes
#
##############################################################

###### Finalize sanity here ######

SANITY_SUBSET := $(TEST_TOOL_ROOTS) $(TEST_ROOTS)

# This section contains recipes for tests other than the default.
# See makefile.default.rules for the default test rules.
# All tests in this section should adhere to the naming convention: <testname>.test

mix-mt.test: $(OBJDIR)mix-mt$(PINTOOL_SUFFIX) $(OBJDIR)marker-example$(EXE_SUFFIX)
	$(PIN) -t $(OBJDIR)mix-mt$(PINTOOL_SUFFIX) -category -start_address marker_start_counting:repeat \
	  -stop_address marker_stop_counting:repeat -zero_stats_address marker_zero_stats:repeat \
	  -emit_stats_address marker_emit_stats:repeat -o $(OBJDIR)mix-mt.out -- $(OBJDIR)marker-example$(EXE_SUFFIX)
	$(RM) $(OBJDIR)mix-mt.out

# MULTITHREADED TEST: mix-mt handles a variable number of threads 
test-mt.test: $(OBJDIR)mix-mt$(PINTOOL_SUFFIX) $(OBJDIR)test-mt$(EXE_SUFFIX)
	$(PIN) -t $(OBJDIR)mix-mt$(PINTOOL_SUFFIX) -start_address marker_start_counting:repeat \
	  -stop_address marker_stop_counting:repeat -zero_stats_address marker_zero_stats:repeat \
	  -emit_stats_address marker_emit_stats:repeat -o $(OBJDIR)test-mt.out -- $(OBJDIR)test-mt$(EXE_SUFFIX)
	$(RM) $(OBJDIR)test-mt.out

# I allow some fuzz in the expected length because sometime we see ~960 and 
# sometimes 1000. This is because the length counter counts blocks and
# that results in approximate counting.
mix-length.test: $(OBJDIR)mix-mt$(PINTOOL_SUFFIX)
	$(PIN) -t $(OBJDIR)mix-mt$(PINTOOL_SUFFIX) -length 1000 -o $(OBJDIR)mix-length.out -- /bin/ls
	$(BASHTEST) `tail $(OBJDIR)mix-length.out | $(GREP) total | gawk '{print $$2}'` -lt 1010
	$(BASHTEST) `tail $(OBJDIR)mix-length.out | $(GREP) total | gawk '{print $$2}'` -gt  960
	$(RM) $(OBJDIR)mix-length.out


##############################################################
#
# Build rules
#
##############################################################

# This section contains the build rules for all binaries that have special build rules.
# See makefile.default.rules for the default build rules.

###### Special tools' build rules ######

ifeq ($(TARGET_OS),windows)
# On Windows, the mix-mt tool needs to be linked with the assy-support object file.
# On all other platforms, simply use the defult build rule.
$(OBJDIR)mix-mt$(PINTOOL_SUFFIX): $(OBJDIR)mix-mt$(OBJ_SUFFIX) $(OBJDIR)assy-support-$(TARGET)$(OBJ_SUFFIX)
	$(LINKER) $(TOOL_LDFLAGS) $(LINK_EXE)$@ $^ $(TOOL_LPATHS) $(TOOL_LIBS)
endif
