/*BEGIN_LEGAL 
Intel Open Source License 

Copyright (c) 2002-2013 Intel Corporation. All rights reserved.
 
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.  Redistributions
in binary form must reproduce the above copyright notice, this list of
conditions and the following disclaimer in the documentation and/or
other materials provided with the distribution.  Neither the name of
the Intel Corporation nor the names of its contributors may be used to
endorse or promote products derived from this software without
specific prior written permission.
 
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE INTEL OR
ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
END_LEGAL */
/// @file xed-gen-table-defs.h

// This file was automatically generated.
// Do not edit this file.

#if !defined(_XED_GEN_TABLE_DEFS_H_)
# define _XED_GEN_TABLE_DEFS_H_
#define XED_ICLASS_NAME_STR_MAX 20
#define XED_MAX_ATTRIBUTE_COUNT 53
#define XED_MAX_INST_TABLE_NODES 3365
#define XED_MAX_OPERAND_TABLE_NODES 902
#define XED_MAX_OPERAND_SEQUENCES 3923
#define XED_MAX_REQUIRED_SIMPLE_FLAGS_ENTRIES 939
#define XED_MAX_REQUIRED_COMPLEX_FLAGS_ENTRIES 53
#define XED_MAX_IFORMS_PER_ICLASS 28
#define XED_MAX_REQUIRED_ATTRIBUTES 110
#define XED_MAX_ACTIONS_PER_SIMPLE_FLAG 20
#define XED_MAX_GLOBAL_FLAG_ACTIONS 4157
#define XED_MAX_CONVERT_PATTERNS 1
#define XED_MAX_DECORATIONS_PER_OPERAND 3
#endif
