/*********************                                                        */
/** options.h
 **
 ** Copyright 2011-2014  New York University and The University of Iowa,
 ** and as below.
 **
 ** This file automatically generated by:
 **
 **     /home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/mkoptions /home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.h ../theory/arith/options.h
 **
 ** for the CVC4 project.
 **/

/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */

/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */

/* Edit the template file instead.                     */

/*********************                                                        */
/*! \file base_options_template.h
 ** \verbatim
 ** Original author: Morgan Deters
 ** Major contributors: none
 ** Minor contributors (to current version): none
 ** This file is part of the CVC4 project.
 ** Copyright (c) 2009-2014  New York University and The University of Iowa
 ** See the file COPYING in the top-level source directory for licensing
 ** information.\endverbatim
 **
 ** \brief Contains code for handling command-line options.
 **
 ** Contains code for handling command-line options
 **/

#include <cvc4/cvc4_public.h>

#ifndef __CVC4__OPTIONS__ARITH_H
#define __CVC4__OPTIONS__ARITH_H

#include <cvc4/options/options.h>

#line 8 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
#include <cvc4/theory/arith/arith_unate_lemma_mode.h>
#line 11 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
#include <cvc4/theory/arith/arith_propagation_mode.h>
#line 28 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
#include <cvc4/theory/arith/arith_heuristic_pivot_rule.h>

#line 26 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.h"

#define CVC4_OPTIONS__ARITH__FOR_OPTION_HOLDER \
  arithUnateLemmaMode__option_t::type arithUnateLemmaMode; \
  bool arithUnateLemmaMode__setByUser__; \
  arithPropagationMode__option_t::type arithPropagationMode; \
  bool arithPropagationMode__setByUser__; \
  arithHeuristicPivots__option_t::type arithHeuristicPivots; \
  bool arithHeuristicPivots__setByUser__; \
  arithStandardCheckVarOrderPivots__option_t::type arithStandardCheckVarOrderPivots; \
  bool arithStandardCheckVarOrderPivots__setByUser__; \
  arithErrorSelectionRule__option_t::type arithErrorSelectionRule; \
  bool arithErrorSelectionRule__setByUser__; \
  arithSimplexCheckPeriod__option_t::type arithSimplexCheckPeriod; \
  bool arithSimplexCheckPeriod__setByUser__; \
  arithPivotThreshold__option_t::type arithPivotThreshold; \
  bool arithPivotThreshold__setByUser__; \
  arithPropagateMaxLength__option_t::type arithPropagateMaxLength; \
  bool arithPropagateMaxLength__setByUser__; \
  arithDioSolver__option_t::type arithDioSolver; \
  bool arithDioSolver__setByUser__; \
  arithRewriteEq__option_t::type arithRewriteEq; \
  bool arithRewriteEq__setByUser__; \
  arithMLTrick__option_t::type arithMLTrick; \
  bool arithMLTrick__setByUser__; \
  arithMLTrickSubstitutions__option_t::type arithMLTrickSubstitutions; \
  bool arithMLTrickSubstitutions__setByUser__; \
  doCutAllBounded__option_t::type doCutAllBounded; \
  bool doCutAllBounded__setByUser__; \
  maxCutsInContext__option_t::type maxCutsInContext; \
  bool maxCutsInContext__setByUser__; \
  revertArithModels__option_t::type revertArithModels; \
  bool revertArithModels__setByUser__; \
  havePenalties__option_t::type havePenalties; \
  bool havePenalties__setByUser__; \
  useFC__option_t::type useFC; \
  bool useFC__setByUser__; \
  useSOI__option_t::type useSOI; \
  bool useSOI__setByUser__; \
  restrictedPivots__option_t::type restrictedPivots; \
  bool restrictedPivots__setByUser__; \
  collectPivots__option_t::type collectPivots; \
  bool collectPivots__setByUser__; \
  useApprox__option_t::type useApprox; \
  bool useApprox__setByUser__; \
  maxApproxDepth__option_t::type maxApproxDepth; \
  bool maxApproxDepth__setByUser__; \
  exportDioDecompositions__option_t::type exportDioDecompositions; \
  bool exportDioDecompositions__setByUser__; \
  newProp__option_t::type newProp; \
  bool newProp__setByUser__; \
  arithPropAsLemmaLength__option_t::type arithPropAsLemmaLength; \
  bool arithPropAsLemmaLength__setByUser__; \
  soiQuickExplain__option_t::type soiQuickExplain; \
  bool soiQuickExplain__setByUser__; \
  rewriteDivk__option_t::type rewriteDivk; \
  bool rewriteDivk__setByUser__; \
  trySolveIntStandardEffort__option_t::type trySolveIntStandardEffort; \
  bool trySolveIntStandardEffort__setByUser__; \
  replayFailureLemma__option_t::type replayFailureLemma; \
  bool replayFailureLemma__setByUser__; \
  dioSolverTurns__option_t::type dioSolverTurns; \
  bool dioSolverTurns__setByUser__; \
  rrTurns__option_t::type rrTurns; \
  bool rrTurns__setByUser__; \
  dioRepeat__option_t::type dioRepeat; \
  bool dioRepeat__setByUser__; \
  replayEarlyCloseDepths__option_t::type replayEarlyCloseDepths; \
  bool replayEarlyCloseDepths__setByUser__; \
  replayFailurePenalty__option_t::type replayFailurePenalty; \
  bool replayFailurePenalty__setByUser__; \
  replayNumericFailurePenalty__option_t::type replayNumericFailurePenalty; \
  bool replayNumericFailurePenalty__setByUser__; \
  replayRejectCutSize__option_t::type replayRejectCutSize; \
  bool replayRejectCutSize__setByUser__; \
  lemmaRejectCutSize__option_t::type lemmaRejectCutSize; \
  bool lemmaRejectCutSize__setByUser__; \
  soiApproxMajorFailure__option_t::type soiApproxMajorFailure; \
  bool soiApproxMajorFailure__setByUser__; \
  soiApproxMajorFailurePen__option_t::type soiApproxMajorFailurePen; \
  bool soiApproxMajorFailurePen__setByUser__; \
  soiApproxMinorFailure__option_t::type soiApproxMinorFailure; \
  bool soiApproxMinorFailure__setByUser__; \
  soiApproxMinorFailurePen__option_t::type soiApproxMinorFailurePen; \
  bool soiApproxMinorFailurePen__setByUser__; \
  ppAssertMaxSubSize__option_t::type ppAssertMaxSubSize; \
  bool ppAssertMaxSubSize__setByUser__; \
  maxReplayTree__option_t::type maxReplayTree; \
  bool maxReplayTree__setByUser__; \
  pbRewrites__option_t::type pbRewrites; \
  bool pbRewrites__setByUser__; \
  pbRewriteThreshold__option_t::type pbRewriteThreshold; \
  bool pbRewriteThreshold__setByUser__;

#line 30 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.h"

namespace CVC4 {

namespace options {


#line 8 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC arithUnateLemmaMode__option_t { typedef ArithUnateLemmaMode type; type operator()() const; bool wasSetByUser() const; } arithUnateLemmaMode CVC4_PUBLIC;
#line 11 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC arithPropagationMode__option_t { typedef ArithPropagationMode type; type operator()() const; bool wasSetByUser() const; } arithPropagationMode CVC4_PUBLIC;
#line 18 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC arithHeuristicPivots__option_t { typedef int16_t type; type operator()() const; bool wasSetByUser() const; void set(const type& v); } arithHeuristicPivots CVC4_PUBLIC;
#line 25 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC arithStandardCheckVarOrderPivots__option_t { typedef int16_t type; type operator()() const; bool wasSetByUser() const; void set(const type& v); } arithStandardCheckVarOrderPivots CVC4_PUBLIC;
#line 28 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC arithErrorSelectionRule__option_t { typedef ErrorSelectionRule type; type operator()() const; bool wasSetByUser() const; } arithErrorSelectionRule CVC4_PUBLIC;
#line 32 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC arithSimplexCheckPeriod__option_t { typedef uint16_t type; type operator()() const; bool wasSetByUser() const; } arithSimplexCheckPeriod CVC4_PUBLIC;
#line 39 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC arithPivotThreshold__option_t { typedef uint16_t type; type operator()() const; bool wasSetByUser() const; void set(const type& v); } arithPivotThreshold CVC4_PUBLIC;
#line 42 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC arithPropagateMaxLength__option_t { typedef uint16_t type; type operator()() const; bool wasSetByUser() const; } arithPropagateMaxLength CVC4_PUBLIC;
#line 45 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC arithDioSolver__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; } arithDioSolver CVC4_PUBLIC;
#line 50 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC arithRewriteEq__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; void set(const type& v); } arithRewriteEq CVC4_PUBLIC;
#line 55 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC arithMLTrick__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; } arithMLTrick CVC4_PUBLIC;
#line 59 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC arithMLTrickSubstitutions__option_t { typedef unsigned type; type operator()() const; bool wasSetByUser() const; } arithMLTrickSubstitutions CVC4_PUBLIC;
#line 62 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC doCutAllBounded__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; void set(const type& v); } doCutAllBounded CVC4_PUBLIC;
#line 66 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC maxCutsInContext__option_t { typedef unsigned type; type operator()() const; bool wasSetByUser() const; } maxCutsInContext CVC4_PUBLIC;
#line 69 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC revertArithModels__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; } revertArithModels CVC4_PUBLIC;
#line 72 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC havePenalties__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; void set(const type& v); } havePenalties CVC4_PUBLIC;
#line 76 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC useFC__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; void set(const type& v); } useFC CVC4_PUBLIC;
#line 79 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC useSOI__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; void set(const type& v); } useSOI CVC4_PUBLIC;
#line 82 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC restrictedPivots__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; void set(const type& v); } restrictedPivots CVC4_PUBLIC;
#line 85 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC collectPivots__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; void set(const type& v); } collectPivots CVC4_PUBLIC;
#line 88 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC useApprox__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; void set(const type& v); } useApprox CVC4_PUBLIC;
#line 91 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC maxApproxDepth__option_t { typedef int16_t type; type operator()() const; bool wasSetByUser() const; void set(const type& v); } maxApproxDepth CVC4_PUBLIC;
#line 94 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC exportDioDecompositions__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; void set(const type& v); } exportDioDecompositions CVC4_PUBLIC;
#line 97 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC newProp__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; void set(const type& v); } newProp CVC4_PUBLIC;
#line 100 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC arithPropAsLemmaLength__option_t { typedef uint16_t type; type operator()() const; bool wasSetByUser() const; void set(const type& v); } arithPropAsLemmaLength CVC4_PUBLIC;
#line 103 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC soiQuickExplain__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; void set(const type& v); } soiQuickExplain CVC4_PUBLIC;
#line 106 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC rewriteDivk__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; void set(const type& v); } rewriteDivk CVC4_PUBLIC;
#line 109 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC trySolveIntStandardEffort__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; } trySolveIntStandardEffort CVC4_PUBLIC;
#line 112 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC replayFailureLemma__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; } replayFailureLemma CVC4_PUBLIC;
#line 115 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC dioSolverTurns__option_t { typedef int type; type operator()() const; bool wasSetByUser() const; } dioSolverTurns CVC4_PUBLIC;
#line 118 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC rrTurns__option_t { typedef int type; type operator()() const; bool wasSetByUser() const; } rrTurns CVC4_PUBLIC;
#line 121 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC dioRepeat__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; } dioRepeat CVC4_PUBLIC;
#line 124 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC replayEarlyCloseDepths__option_t { typedef int type; type operator()() const; bool wasSetByUser() const; } replayEarlyCloseDepths CVC4_PUBLIC;
#line 127 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC replayFailurePenalty__option_t { typedef int type; type operator()() const; bool wasSetByUser() const; } replayFailurePenalty CVC4_PUBLIC;
#line 130 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC replayNumericFailurePenalty__option_t { typedef int type; type operator()() const; bool wasSetByUser() const; } replayNumericFailurePenalty CVC4_PUBLIC;
#line 133 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC replayRejectCutSize__option_t { typedef unsigned type; type operator()() const; bool wasSetByUser() const; } replayRejectCutSize CVC4_PUBLIC;
#line 136 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC lemmaRejectCutSize__option_t { typedef unsigned type; type operator()() const; bool wasSetByUser() const; } lemmaRejectCutSize CVC4_PUBLIC;
#line 139 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC soiApproxMajorFailure__option_t { typedef double type; type operator()() const; bool wasSetByUser() const; } soiApproxMajorFailure CVC4_PUBLIC;
#line 142 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC soiApproxMajorFailurePen__option_t { typedef int type; type operator()() const; bool wasSetByUser() const; } soiApproxMajorFailurePen CVC4_PUBLIC;
#line 145 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC soiApproxMinorFailure__option_t { typedef double type; type operator()() const; bool wasSetByUser() const; } soiApproxMinorFailure CVC4_PUBLIC;
#line 148 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC soiApproxMinorFailurePen__option_t { typedef int type; type operator()() const; bool wasSetByUser() const; } soiApproxMinorFailurePen CVC4_PUBLIC;
#line 151 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC ppAssertMaxSubSize__option_t { typedef unsigned type; type operator()() const; bool wasSetByUser() const; } ppAssertMaxSubSize CVC4_PUBLIC;
#line 154 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC maxReplayTree__option_t { typedef int type; type operator()() const; bool wasSetByUser() const; } maxReplayTree CVC4_PUBLIC;
#line 158 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC pbRewrites__option_t { typedef bool type; type operator()() const; bool wasSetByUser() const; } pbRewrites CVC4_PUBLIC;
#line 161 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
extern struct CVC4_PUBLIC pbRewriteThreshold__option_t { typedef int type; type operator()() const; bool wasSetByUser() const; } pbRewriteThreshold CVC4_PUBLIC;

#line 38 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.h"

}/* CVC4::options namespace */


#line 8 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithUnateLemmaMode__option_t::type& Options::operator[](options::arithUnateLemmaMode__option_t) const;
#line 8 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithUnateLemmaMode__option_t) const;
#line 8 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::arithUnateLemmaMode__option_t, std::string option, std::string value, SmtEngine* smt);
#line 11 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithPropagationMode__option_t::type& Options::operator[](options::arithPropagationMode__option_t) const;
#line 11 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithPropagationMode__option_t) const;
#line 11 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::arithPropagationMode__option_t, std::string option, std::string value, SmtEngine* smt);
#line 18 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::arithHeuristicPivots__option_t, const options::arithHeuristicPivots__option_t::type& x);
#line 18 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithHeuristicPivots__option_t::type& Options::operator[](options::arithHeuristicPivots__option_t) const;
#line 18 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithHeuristicPivots__option_t) const;
#line 18 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::arithHeuristicPivots__option_t, std::string option, std::string value, SmtEngine* smt);
#line 25 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::arithStandardCheckVarOrderPivots__option_t, const options::arithStandardCheckVarOrderPivots__option_t::type& x);
#line 25 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithStandardCheckVarOrderPivots__option_t::type& Options::operator[](options::arithStandardCheckVarOrderPivots__option_t) const;
#line 25 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithStandardCheckVarOrderPivots__option_t) const;
#line 25 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::arithStandardCheckVarOrderPivots__option_t, std::string option, std::string value, SmtEngine* smt);
#line 28 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithErrorSelectionRule__option_t::type& Options::operator[](options::arithErrorSelectionRule__option_t) const;
#line 28 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithErrorSelectionRule__option_t) const;
#line 28 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::arithErrorSelectionRule__option_t, std::string option, std::string value, SmtEngine* smt);
#line 32 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithSimplexCheckPeriod__option_t::type& Options::operator[](options::arithSimplexCheckPeriod__option_t) const;
#line 32 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithSimplexCheckPeriod__option_t) const;
#line 32 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::arithSimplexCheckPeriod__option_t, std::string option, std::string value, SmtEngine* smt);
#line 39 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::arithPivotThreshold__option_t, const options::arithPivotThreshold__option_t::type& x);
#line 39 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithPivotThreshold__option_t::type& Options::operator[](options::arithPivotThreshold__option_t) const;
#line 39 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithPivotThreshold__option_t) const;
#line 39 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::arithPivotThreshold__option_t, std::string option, std::string value, SmtEngine* smt);
#line 42 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithPropagateMaxLength__option_t::type& Options::operator[](options::arithPropagateMaxLength__option_t) const;
#line 42 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithPropagateMaxLength__option_t) const;
#line 42 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::arithPropagateMaxLength__option_t, std::string option, std::string value, SmtEngine* smt);
#line 45 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithDioSolver__option_t::type& Options::operator[](options::arithDioSolver__option_t) const;
#line 45 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithDioSolver__option_t) const;
#line 45 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assignBool(options::arithDioSolver__option_t, std::string option, bool value, SmtEngine* smt);
#line 50 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::arithRewriteEq__option_t, const options::arithRewriteEq__option_t::type& x);
#line 50 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithRewriteEq__option_t::type& Options::operator[](options::arithRewriteEq__option_t) const;
#line 50 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithRewriteEq__option_t) const;
#line 50 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assignBool(options::arithRewriteEq__option_t, std::string option, bool value, SmtEngine* smt);
#line 55 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithMLTrick__option_t::type& Options::operator[](options::arithMLTrick__option_t) const;
#line 55 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithMLTrick__option_t) const;
#line 55 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assignBool(options::arithMLTrick__option_t, std::string option, bool value, SmtEngine* smt);
#line 59 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithMLTrickSubstitutions__option_t::type& Options::operator[](options::arithMLTrickSubstitutions__option_t) const;
#line 59 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithMLTrickSubstitutions__option_t) const;
#line 59 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::arithMLTrickSubstitutions__option_t, std::string option, std::string value, SmtEngine* smt);
#line 62 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::doCutAllBounded__option_t, const options::doCutAllBounded__option_t::type& x);
#line 62 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::doCutAllBounded__option_t::type& Options::operator[](options::doCutAllBounded__option_t) const;
#line 62 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::doCutAllBounded__option_t) const;
#line 62 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assignBool(options::doCutAllBounded__option_t, std::string option, bool value, SmtEngine* smt);
#line 66 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::maxCutsInContext__option_t::type& Options::operator[](options::maxCutsInContext__option_t) const;
#line 66 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::maxCutsInContext__option_t) const;
#line 66 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::maxCutsInContext__option_t, std::string option, std::string value, SmtEngine* smt);
#line 69 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::revertArithModels__option_t::type& Options::operator[](options::revertArithModels__option_t) const;
#line 69 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::revertArithModels__option_t) const;
#line 69 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assignBool(options::revertArithModels__option_t, std::string option, bool value, SmtEngine* smt);
#line 72 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::havePenalties__option_t, const options::havePenalties__option_t::type& x);
#line 72 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::havePenalties__option_t::type& Options::operator[](options::havePenalties__option_t) const;
#line 72 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::havePenalties__option_t) const;
#line 72 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assignBool(options::havePenalties__option_t, std::string option, bool value, SmtEngine* smt);
#line 76 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::useFC__option_t, const options::useFC__option_t::type& x);
#line 76 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::useFC__option_t::type& Options::operator[](options::useFC__option_t) const;
#line 76 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::useFC__option_t) const;
#line 76 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assignBool(options::useFC__option_t, std::string option, bool value, SmtEngine* smt);
#line 79 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::useSOI__option_t, const options::useSOI__option_t::type& x);
#line 79 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::useSOI__option_t::type& Options::operator[](options::useSOI__option_t) const;
#line 79 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::useSOI__option_t) const;
#line 79 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assignBool(options::useSOI__option_t, std::string option, bool value, SmtEngine* smt);
#line 82 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::restrictedPivots__option_t, const options::restrictedPivots__option_t::type& x);
#line 82 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::restrictedPivots__option_t::type& Options::operator[](options::restrictedPivots__option_t) const;
#line 82 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::restrictedPivots__option_t) const;
#line 82 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assignBool(options::restrictedPivots__option_t, std::string option, bool value, SmtEngine* smt);
#line 85 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::collectPivots__option_t, const options::collectPivots__option_t::type& x);
#line 85 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::collectPivots__option_t::type& Options::operator[](options::collectPivots__option_t) const;
#line 85 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::collectPivots__option_t) const;
#line 85 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assignBool(options::collectPivots__option_t, std::string option, bool value, SmtEngine* smt);
#line 88 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::useApprox__option_t, const options::useApprox__option_t::type& x);
#line 88 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::useApprox__option_t::type& Options::operator[](options::useApprox__option_t) const;
#line 88 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::useApprox__option_t) const;
#line 88 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assignBool(options::useApprox__option_t, std::string option, bool value, SmtEngine* smt);
#line 91 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::maxApproxDepth__option_t, const options::maxApproxDepth__option_t::type& x);
#line 91 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::maxApproxDepth__option_t::type& Options::operator[](options::maxApproxDepth__option_t) const;
#line 91 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::maxApproxDepth__option_t) const;
#line 91 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::maxApproxDepth__option_t, std::string option, std::string value, SmtEngine* smt);
#line 94 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::exportDioDecompositions__option_t, const options::exportDioDecompositions__option_t::type& x);
#line 94 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::exportDioDecompositions__option_t::type& Options::operator[](options::exportDioDecompositions__option_t) const;
#line 94 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::exportDioDecompositions__option_t) const;
#line 94 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assignBool(options::exportDioDecompositions__option_t, std::string option, bool value, SmtEngine* smt);
#line 97 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::newProp__option_t, const options::newProp__option_t::type& x);
#line 97 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::newProp__option_t::type& Options::operator[](options::newProp__option_t) const;
#line 97 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::newProp__option_t) const;
#line 97 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assignBool(options::newProp__option_t, std::string option, bool value, SmtEngine* smt);
#line 100 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::arithPropAsLemmaLength__option_t, const options::arithPropAsLemmaLength__option_t::type& x);
#line 100 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithPropAsLemmaLength__option_t::type& Options::operator[](options::arithPropAsLemmaLength__option_t) const;
#line 100 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithPropAsLemmaLength__option_t) const;
#line 100 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::arithPropAsLemmaLength__option_t, std::string option, std::string value, SmtEngine* smt);
#line 103 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::soiQuickExplain__option_t, const options::soiQuickExplain__option_t::type& x);
#line 103 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::soiQuickExplain__option_t::type& Options::operator[](options::soiQuickExplain__option_t) const;
#line 103 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::soiQuickExplain__option_t) const;
#line 103 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assignBool(options::soiQuickExplain__option_t, std::string option, bool value, SmtEngine* smt);
#line 106 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::rewriteDivk__option_t, const options::rewriteDivk__option_t::type& x);
#line 106 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::rewriteDivk__option_t::type& Options::operator[](options::rewriteDivk__option_t) const;
#line 106 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::rewriteDivk__option_t) const;
#line 106 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assignBool(options::rewriteDivk__option_t, std::string option, bool value, SmtEngine* smt);
#line 109 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::trySolveIntStandardEffort__option_t::type& Options::operator[](options::trySolveIntStandardEffort__option_t) const;
#line 109 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::trySolveIntStandardEffort__option_t) const;
#line 109 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assignBool(options::trySolveIntStandardEffort__option_t, std::string option, bool value, SmtEngine* smt);
#line 112 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::replayFailureLemma__option_t::type& Options::operator[](options::replayFailureLemma__option_t) const;
#line 112 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::replayFailureLemma__option_t) const;
#line 112 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assignBool(options::replayFailureLemma__option_t, std::string option, bool value, SmtEngine* smt);
#line 115 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::dioSolverTurns__option_t::type& Options::operator[](options::dioSolverTurns__option_t) const;
#line 115 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::dioSolverTurns__option_t) const;
#line 115 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::dioSolverTurns__option_t, std::string option, std::string value, SmtEngine* smt);
#line 118 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::rrTurns__option_t::type& Options::operator[](options::rrTurns__option_t) const;
#line 118 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::rrTurns__option_t) const;
#line 118 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::rrTurns__option_t, std::string option, std::string value, SmtEngine* smt);
#line 121 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::dioRepeat__option_t::type& Options::operator[](options::dioRepeat__option_t) const;
#line 121 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::dioRepeat__option_t) const;
#line 121 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assignBool(options::dioRepeat__option_t, std::string option, bool value, SmtEngine* smt);
#line 124 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::replayEarlyCloseDepths__option_t::type& Options::operator[](options::replayEarlyCloseDepths__option_t) const;
#line 124 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::replayEarlyCloseDepths__option_t) const;
#line 124 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::replayEarlyCloseDepths__option_t, std::string option, std::string value, SmtEngine* smt);
#line 127 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::replayFailurePenalty__option_t::type& Options::operator[](options::replayFailurePenalty__option_t) const;
#line 127 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::replayFailurePenalty__option_t) const;
#line 127 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::replayFailurePenalty__option_t, std::string option, std::string value, SmtEngine* smt);
#line 130 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::replayNumericFailurePenalty__option_t::type& Options::operator[](options::replayNumericFailurePenalty__option_t) const;
#line 130 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::replayNumericFailurePenalty__option_t) const;
#line 130 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::replayNumericFailurePenalty__option_t, std::string option, std::string value, SmtEngine* smt);
#line 133 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::replayRejectCutSize__option_t::type& Options::operator[](options::replayRejectCutSize__option_t) const;
#line 133 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::replayRejectCutSize__option_t) const;
#line 133 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::replayRejectCutSize__option_t, std::string option, std::string value, SmtEngine* smt);
#line 136 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::lemmaRejectCutSize__option_t::type& Options::operator[](options::lemmaRejectCutSize__option_t) const;
#line 136 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::lemmaRejectCutSize__option_t) const;
#line 136 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::lemmaRejectCutSize__option_t, std::string option, std::string value, SmtEngine* smt);
#line 139 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::soiApproxMajorFailure__option_t::type& Options::operator[](options::soiApproxMajorFailure__option_t) const;
#line 139 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::soiApproxMajorFailure__option_t) const;
#line 139 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::soiApproxMajorFailure__option_t, std::string option, std::string value, SmtEngine* smt);
#line 142 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::soiApproxMajorFailurePen__option_t::type& Options::operator[](options::soiApproxMajorFailurePen__option_t) const;
#line 142 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::soiApproxMajorFailurePen__option_t) const;
#line 142 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::soiApproxMajorFailurePen__option_t, std::string option, std::string value, SmtEngine* smt);
#line 145 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::soiApproxMinorFailure__option_t::type& Options::operator[](options::soiApproxMinorFailure__option_t) const;
#line 145 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::soiApproxMinorFailure__option_t) const;
#line 145 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::soiApproxMinorFailure__option_t, std::string option, std::string value, SmtEngine* smt);
#line 148 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::soiApproxMinorFailurePen__option_t::type& Options::operator[](options::soiApproxMinorFailurePen__option_t) const;
#line 148 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::soiApproxMinorFailurePen__option_t) const;
#line 148 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::soiApproxMinorFailurePen__option_t, std::string option, std::string value, SmtEngine* smt);
#line 151 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::ppAssertMaxSubSize__option_t::type& Options::operator[](options::ppAssertMaxSubSize__option_t) const;
#line 151 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::ppAssertMaxSubSize__option_t) const;
#line 151 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::ppAssertMaxSubSize__option_t, std::string option, std::string value, SmtEngine* smt);
#line 154 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::maxReplayTree__option_t::type& Options::operator[](options::maxReplayTree__option_t) const;
#line 154 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::maxReplayTree__option_t) const;
#line 154 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::maxReplayTree__option_t, std::string option, std::string value, SmtEngine* smt);
#line 158 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::pbRewrites__option_t::type& Options::operator[](options::pbRewrites__option_t) const;
#line 158 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::pbRewrites__option_t) const;
#line 158 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assignBool(options::pbRewrites__option_t, std::string option, bool value, SmtEngine* smt);
#line 161 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::pbRewriteThreshold__option_t::type& Options::operator[](options::pbRewriteThreshold__option_t) const;
#line 161 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::pbRewriteThreshold__option_t) const;
#line 161 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::assign(options::pbRewriteThreshold__option_t, std::string option, std::string value, SmtEngine* smt);

#line 44 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.h"

namespace options {


#line 8 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline arithUnateLemmaMode__option_t::type arithUnateLemmaMode__option_t::operator()() const { return Options::current()[*this]; }
#line 8 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool arithUnateLemmaMode__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 11 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline arithPropagationMode__option_t::type arithPropagationMode__option_t::operator()() const { return Options::current()[*this]; }
#line 11 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool arithPropagationMode__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 18 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline arithHeuristicPivots__option_t::type arithHeuristicPivots__option_t::operator()() const { return Options::current()[*this]; }
#line 18 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool arithHeuristicPivots__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }
#line 18 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline void arithHeuristicPivots__option_t::set(const arithHeuristicPivots__option_t::type& v) { Options::current().set(*this, v); }

#line 25 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline arithStandardCheckVarOrderPivots__option_t::type arithStandardCheckVarOrderPivots__option_t::operator()() const { return Options::current()[*this]; }
#line 25 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool arithStandardCheckVarOrderPivots__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }
#line 25 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline void arithStandardCheckVarOrderPivots__option_t::set(const arithStandardCheckVarOrderPivots__option_t::type& v) { Options::current().set(*this, v); }

#line 28 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline arithErrorSelectionRule__option_t::type arithErrorSelectionRule__option_t::operator()() const { return Options::current()[*this]; }
#line 28 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool arithErrorSelectionRule__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 32 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline arithSimplexCheckPeriod__option_t::type arithSimplexCheckPeriod__option_t::operator()() const { return Options::current()[*this]; }
#line 32 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool arithSimplexCheckPeriod__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 39 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline arithPivotThreshold__option_t::type arithPivotThreshold__option_t::operator()() const { return Options::current()[*this]; }
#line 39 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool arithPivotThreshold__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }
#line 39 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline void arithPivotThreshold__option_t::set(const arithPivotThreshold__option_t::type& v) { Options::current().set(*this, v); }

#line 42 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline arithPropagateMaxLength__option_t::type arithPropagateMaxLength__option_t::operator()() const { return Options::current()[*this]; }
#line 42 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool arithPropagateMaxLength__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 45 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline arithDioSolver__option_t::type arithDioSolver__option_t::operator()() const { return Options::current()[*this]; }
#line 45 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool arithDioSolver__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 50 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline arithRewriteEq__option_t::type arithRewriteEq__option_t::operator()() const { return Options::current()[*this]; }
#line 50 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool arithRewriteEq__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }
#line 50 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline void arithRewriteEq__option_t::set(const arithRewriteEq__option_t::type& v) { Options::current().set(*this, v); }

#line 55 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline arithMLTrick__option_t::type arithMLTrick__option_t::operator()() const { return Options::current()[*this]; }
#line 55 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool arithMLTrick__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 59 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline arithMLTrickSubstitutions__option_t::type arithMLTrickSubstitutions__option_t::operator()() const { return Options::current()[*this]; }
#line 59 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool arithMLTrickSubstitutions__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 62 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline doCutAllBounded__option_t::type doCutAllBounded__option_t::operator()() const { return Options::current()[*this]; }
#line 62 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool doCutAllBounded__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }
#line 62 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline void doCutAllBounded__option_t::set(const doCutAllBounded__option_t::type& v) { Options::current().set(*this, v); }

#line 66 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline maxCutsInContext__option_t::type maxCutsInContext__option_t::operator()() const { return Options::current()[*this]; }
#line 66 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool maxCutsInContext__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 69 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline revertArithModels__option_t::type revertArithModels__option_t::operator()() const { return Options::current()[*this]; }
#line 69 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool revertArithModels__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 72 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline havePenalties__option_t::type havePenalties__option_t::operator()() const { return Options::current()[*this]; }
#line 72 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool havePenalties__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }
#line 72 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline void havePenalties__option_t::set(const havePenalties__option_t::type& v) { Options::current().set(*this, v); }

#line 76 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline useFC__option_t::type useFC__option_t::operator()() const { return Options::current()[*this]; }
#line 76 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool useFC__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }
#line 76 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline void useFC__option_t::set(const useFC__option_t::type& v) { Options::current().set(*this, v); }

#line 79 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline useSOI__option_t::type useSOI__option_t::operator()() const { return Options::current()[*this]; }
#line 79 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool useSOI__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }
#line 79 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline void useSOI__option_t::set(const useSOI__option_t::type& v) { Options::current().set(*this, v); }

#line 82 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline restrictedPivots__option_t::type restrictedPivots__option_t::operator()() const { return Options::current()[*this]; }
#line 82 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool restrictedPivots__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }
#line 82 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline void restrictedPivots__option_t::set(const restrictedPivots__option_t::type& v) { Options::current().set(*this, v); }

#line 85 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline collectPivots__option_t::type collectPivots__option_t::operator()() const { return Options::current()[*this]; }
#line 85 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool collectPivots__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }
#line 85 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline void collectPivots__option_t::set(const collectPivots__option_t::type& v) { Options::current().set(*this, v); }

#line 88 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline useApprox__option_t::type useApprox__option_t::operator()() const { return Options::current()[*this]; }
#line 88 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool useApprox__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }
#line 88 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline void useApprox__option_t::set(const useApprox__option_t::type& v) { Options::current().set(*this, v); }

#line 91 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline maxApproxDepth__option_t::type maxApproxDepth__option_t::operator()() const { return Options::current()[*this]; }
#line 91 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool maxApproxDepth__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }
#line 91 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline void maxApproxDepth__option_t::set(const maxApproxDepth__option_t::type& v) { Options::current().set(*this, v); }

#line 94 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline exportDioDecompositions__option_t::type exportDioDecompositions__option_t::operator()() const { return Options::current()[*this]; }
#line 94 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool exportDioDecompositions__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }
#line 94 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline void exportDioDecompositions__option_t::set(const exportDioDecompositions__option_t::type& v) { Options::current().set(*this, v); }

#line 97 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline newProp__option_t::type newProp__option_t::operator()() const { return Options::current()[*this]; }
#line 97 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool newProp__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }
#line 97 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline void newProp__option_t::set(const newProp__option_t::type& v) { Options::current().set(*this, v); }

#line 100 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline arithPropAsLemmaLength__option_t::type arithPropAsLemmaLength__option_t::operator()() const { return Options::current()[*this]; }
#line 100 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool arithPropAsLemmaLength__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }
#line 100 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline void arithPropAsLemmaLength__option_t::set(const arithPropAsLemmaLength__option_t::type& v) { Options::current().set(*this, v); }

#line 103 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline soiQuickExplain__option_t::type soiQuickExplain__option_t::operator()() const { return Options::current()[*this]; }
#line 103 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool soiQuickExplain__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }
#line 103 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline void soiQuickExplain__option_t::set(const soiQuickExplain__option_t::type& v) { Options::current().set(*this, v); }

#line 106 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline rewriteDivk__option_t::type rewriteDivk__option_t::operator()() const { return Options::current()[*this]; }
#line 106 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool rewriteDivk__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }
#line 106 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline void rewriteDivk__option_t::set(const rewriteDivk__option_t::type& v) { Options::current().set(*this, v); }

#line 109 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline trySolveIntStandardEffort__option_t::type trySolveIntStandardEffort__option_t::operator()() const { return Options::current()[*this]; }
#line 109 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool trySolveIntStandardEffort__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 112 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline replayFailureLemma__option_t::type replayFailureLemma__option_t::operator()() const { return Options::current()[*this]; }
#line 112 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool replayFailureLemma__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 115 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline dioSolverTurns__option_t::type dioSolverTurns__option_t::operator()() const { return Options::current()[*this]; }
#line 115 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool dioSolverTurns__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 118 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline rrTurns__option_t::type rrTurns__option_t::operator()() const { return Options::current()[*this]; }
#line 118 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool rrTurns__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 121 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline dioRepeat__option_t::type dioRepeat__option_t::operator()() const { return Options::current()[*this]; }
#line 121 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool dioRepeat__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 124 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline replayEarlyCloseDepths__option_t::type replayEarlyCloseDepths__option_t::operator()() const { return Options::current()[*this]; }
#line 124 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool replayEarlyCloseDepths__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 127 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline replayFailurePenalty__option_t::type replayFailurePenalty__option_t::operator()() const { return Options::current()[*this]; }
#line 127 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool replayFailurePenalty__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 130 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline replayNumericFailurePenalty__option_t::type replayNumericFailurePenalty__option_t::operator()() const { return Options::current()[*this]; }
#line 130 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool replayNumericFailurePenalty__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 133 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline replayRejectCutSize__option_t::type replayRejectCutSize__option_t::operator()() const { return Options::current()[*this]; }
#line 133 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool replayRejectCutSize__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 136 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline lemmaRejectCutSize__option_t::type lemmaRejectCutSize__option_t::operator()() const { return Options::current()[*this]; }
#line 136 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool lemmaRejectCutSize__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 139 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline soiApproxMajorFailure__option_t::type soiApproxMajorFailure__option_t::operator()() const { return Options::current()[*this]; }
#line 139 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool soiApproxMajorFailure__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 142 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline soiApproxMajorFailurePen__option_t::type soiApproxMajorFailurePen__option_t::operator()() const { return Options::current()[*this]; }
#line 142 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool soiApproxMajorFailurePen__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 145 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline soiApproxMinorFailure__option_t::type soiApproxMinorFailure__option_t::operator()() const { return Options::current()[*this]; }
#line 145 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool soiApproxMinorFailure__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 148 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline soiApproxMinorFailurePen__option_t::type soiApproxMinorFailurePen__option_t::operator()() const { return Options::current()[*this]; }
#line 148 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool soiApproxMinorFailurePen__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 151 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline ppAssertMaxSubSize__option_t::type ppAssertMaxSubSize__option_t::operator()() const { return Options::current()[*this]; }
#line 151 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool ppAssertMaxSubSize__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 154 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline maxReplayTree__option_t::type maxReplayTree__option_t::operator()() const { return Options::current()[*this]; }
#line 154 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool maxReplayTree__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 158 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline pbRewrites__option_t::type pbRewrites__option_t::operator()() const { return Options::current()[*this]; }
#line 158 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool pbRewrites__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 161 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline pbRewriteThreshold__option_t::type pbRewriteThreshold__option_t::operator()() const { return Options::current()[*this]; }
#line 161 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
inline bool pbRewriteThreshold__option_t::wasSetByUser() const { return Options::current().wasSetByUser(*this); }

#line 50 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.h"

}/* CVC4::options namespace */

}/* CVC4 namespace */

#endif /* __CVC4__OPTIONS__ARITH_H */
