#!/bin/bash

DIR=$1
OUTFILE=$1/handlers.h

if [ "$#" -ne 1 ]; then
  echo "USAGE: $0 <directory of tests/validator>"
  exit 1
fi

echo "// handlers.h" > $OUTFILE
echo "// WARNING: this file is autogenerated.  See $0." >> $OUTFILE
echo "" >> $OUTFILE
ls -1 $DIR/handlers | sed "s/^/#include \"tests\/validator\/handlers\//g" | sed "s/$/\"/g" >> $OUTFILE
echo "" >> $OUTFILE

exit 0
