
# This file was *autogenerated* from the file files2nlfK.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_16 = Integer(16); _sage_const_9223372036854775808 = Integer(9223372036854775808); _sage_const_921870150625286144 = Integer(921870150625286144); _sage_const_18 = Integer(18); _sage_const_9216169926303015760 = Integer(9216169926303015760)
f = open("/tmp/filee73V9p.out", 'w')
rows=_sage_const_1 
cols=_sage_const_18 
ZZ=IntegerRing()
A = MatrixSpace(ZZ, rows, cols)([_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , -_sage_const_9223372036854775808 , _sage_const_9216169926303015760 , _sage_const_16 , -_sage_const_921870150625286144 , -_sage_const_9216169926303015760 ])
D,U,V=A.smith_form()
min_dim = min(rows,cols)
diagonals = [ D[i][i] for i in range(_sage_const_0 ,min_dim) if D[i][i] != _sage_const_0 ]
nz_diag = len(diagonals)
bv_len = len(V.rows())
basis = [ [_sage_const_0 ]*nz_diag + [_sage_const_0 ]*i + [_sage_const_1 ] + [_sage_const_0 ]*(bv_len-nz_diag-i-_sage_const_1 ) for i in range(_sage_const_0 ,bv_len-nz_diag)]
dim = len(basis)
outputs = [ V*vector(b) for b in basis ]
print >>f, len(outputs), len(outputs[_sage_const_0 ])
print "test"
for output in outputs:
	print >>f, " ".join(map(lambda x:str(x), output))
f.close()



