##############################################################
#
# This file includes all the test targets as well as all the
# non-default build rules and test recipes.
#
##############################################################


##############################################################
#
# Test targets
#
##############################################################

###### Place all generic definitions here ######

# This defines tests which run tools of the same name.  This is simply for convenience to avoid
# defining the test name twice (once in TOOL_ROOTS and again in TEST_ROOTS).
# Tests defined here should not be defined in TOOL_ROOTS and TEST_ROOTS.
TEST_TOOL_ROOTS := bufferaddr two_buffers allocate mlog_buffer buffer-then buffer-predicate buffererror buffer-lengths

# This defines the tests to be run that were not already defined in TEST_TOOL_ROOTS.
TEST_ROOTS :=

# This defines a list of tests that should run in the "short" sanity. Tests in this list must also
# appear either in the TEST_TOOL_ROOTS or the TEST_ROOTS list.
# If the entire directory should be tested in sanity, assign TEST_TOOL_ROOTS and TEST_ROOTS to the
# SANITY_SUBSET variable in the tests section below (see example in makefile.rules.tmpl).
SANITY_SUBSET :=

# This defines the tools which will be run during the the tests, and were not already defined in
# TEST_TOOL_ROOTS.
TOOL_ROOTS :=

# This defines the static analysis tools which will be run during the the tests. They should not
# be defined in TEST_TOOL_ROOTS. If a test with the same name exists, it should be defined in
# TEST_ROOTS.
# Note: Static analysis tools are in fact executables linked with the Pin Static Analysis Library.
# This library provides a subset of the Pin APIs which allows the tool to perform static analysis
# of an application or dll. Pin itself is not used when this tool runs.
SA_TOOL_ROOTS :=

# This defines all the applications that will be run during the tests.
APP_ROOTS :=

# This defines any additional object files that need to be compiled.
OBJECT_ROOTS :=

# This defines any additional dlls (shared objects), other than the pintools, that need to be compiled.
DLL_ROOTS :=

# This defines any static libraries (archives), that need to be built.
LIB_ROOTS :=

###### Handle exceptions here ######

# TODO: These tests fail - fix and remove the following:
# See mantis 2963
ifeq ($(TARGET),mic)
    TEST_TOOL_ROOTS := $(filter-out buffer-then mlog_buffer allocate two_buffers, $(TEST_TOOL_ROOTS))
endif


##############################################################
#
# Test recipes
#
##############################################################

###### Finalize sanity here ######

SANITY_SUBSET := $(TEST_TOOL_ROOTS) $(TEST_ROOTS)

# This section contains recipes for tests other than the default.
# See makefile.default.rules for the default test rules.
# All tests in this section should adhere to the naming convention: <testname>.test

bufferaddr.test: $(OBJDIR)bufferaddr$(PINTOOL_SUFFIX) $(TESTAPP)
	$(PIN) -xyzzy -mesgon log_buffer -logfile $(OBJDIR)bufferaddr.log -t $(OBJDIR)bufferaddr$(PINTOOL_SUFFIX) \
	  -- $(TESTAPP) makefile $(OBJDIR)bufferaddr.makefile.copy
	$(QGREP) -e "Allocated buffer" $(OBJDIR)bufferaddr.log
	$(RM) $(OBJDIR)bufferaddr.log $(OBJDIR)bufferaddr.makefile.copy

two_buffers.test: $(OBJDIR)two_buffers$(PINTOOL_SUFFIX) $(TESTAPP)
	$(PIN) -xyzzy -mesgon log_buffer -logfile $(OBJDIR)two_buffers.log -t $(OBJDIR)two_buffers$(PINTOOL_SUFFIX) \
	  -- $(TESTAPP) makefile $(OBJDIR)two_buffers.makefile.copy
	$(QGREP) -e "buffer 1" two_buffers.out
	$(QGREP) -e "buffer 2" two_buffers.out
	$(RM) $(OBJDIR)two_buffers.log $(OBJDIR)two_buffers.makefile.copy

allocate.test: $(OBJDIR)allocate$(PINTOOL_SUFFIX) $(TESTAPP)
	$(PIN) -xyzzy -mesgon log_buffer -logfile $(OBJDIR)allocate.log -t $(OBJDIR)allocate$(PINTOOL_SUFFIX) \
	  -- $(TESTAPP) makefile $(OBJDIR)allocate.makefile.copy
	$(QGREP) -e "found buffer" $(OBJDIR)allocate.log
	$(RM) $(OBJDIR)allocate.log $(OBJDIR)allocate.makefile.copy

buffer-then.test: $(OBJDIR)buffer-then$(PINTOOL_SUFFIX) $(TESTAPP)
	$(PIN) -t $(OBJDIR)buffer-then$(PINTOOL_SUFFIX) -- $(TESTAPP) makefile $(OBJDIR)buffer-then.makefile.copy \
	  > $(OBJDIR)buffer-then.out 2>&1
	$(RM) $(OBJDIR)buffer-then.out $(OBJDIR)buffer-then.makefile.copy

buffer-predicate.test: $(OBJDIR)buffer-predicate$(PINTOOL_SUFFIX) $(TESTAPP)
	$(PIN) -t $(OBJDIR)buffer-predicate$(PINTOOL_SUFFIX) \
	  -- $(TESTAPP) makefile $(OBJDIR)buffer-predicate.makefile.copy > $(OBJDIR)buffer-predicate.out 2>&1
	$(RM) $(OBJDIR)buffer-predicate.out $(OBJDIR)buffer-predicate.makefile.copy

buffer-lengths.test: $(OBJDIR)buffer-lengths$(PINTOOL_SUFFIX) $(TESTAPP)
	$(PIN) -t $(OBJDIR)buffer-lengths$(PINTOOL_SUFFIX) \
	  -- $(TESTAPP) makefile $(OBJDIR)buffer-lengths.makefile.copy
	$(GREP) -e "Test passed" buffer-lengths.out
	$(RM) buffer-lengths.out $(OBJDIR)buffer-lengths.makefile.copy

# This is a negative test, it should fail.
buffererror.test: $(OBJDIR)buffererror$(PINTOOL_SUFFIX) $(TESTAPP)
	-$(PIN) -xyzzy -mesgon log_buffer -logfile $(OBJDIR)buffererror.log -t $(OBJDIR)buffererror$(PINTOOL_SUFFIX) \
	  -- $(TESTAPP) makefile $(OBJDIR)buffererror.makefile.copy
	echo "buffererror is a negative test.  Ignore the failure."
	$(QGREP) "IARG_REG_REFERENCE" $(OBJDIR)buffererror.log
	$(RM) $(OBJDIR)buffererror.log


##############################################################
#
# Build rules
#
##############################################################

# This section contains the build rules for all binaries that have special build rules.
# See makefile.default.rules for the default build rules.
